runtime: python37

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /images
    static_dir: static/images

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

error_handlers:
  - file: app/templates/errors/default_error.html

  - error_code: over_quota
    file: app/templates/errors/over_quota.html

automatic_scaling:
  max_instances: 1

# entrypoint: gunicorn --workers=2 __init__:breadapp
