# https://yamlchecker.com/
runtime: python
env: flex

instance_class: F1

entrypoint: gunicorn -w 2 breadsheet:breadapp --timeout 90

error_handlers:
  - file: app/templates/errors/default_error.html

  - error_code: over_quota
    file: app/templates/errors/over_quota.html

beta_settings:
  cloud_sql_instances: breadsheet:us-west1:breadsheet

env_variables:
  SQLALCHEMY_DATABASE_URI: postgres+psycopg2://USER:PW@/breadsheet?host=/cloudsql/breadsheet:us-west1:breadsheet
