# https://yamlchecker.com/
runtime: python37

instance_class: F1

env_variables:
  BUCKET_NAME: "breadsheet.appspot.com"

entrypoint: gunicorn -w 1 breadsheet:breadapp

handlers:
  # Matches requests for /images ... to files in static/images/
  - url: /images
    static_dir: static/images

error_handlers:
  - file: app/templates/errors/default_error.html

  - error_code: over_quota
    file: app/templates/errors/over_quota.html

automatic_scaling:
  max_instances: 1
