# https://yamlchecker.com/
runtime: python37

# instance_class: F1
#   defaults to F1 anyway

# entrypoint: gunicorn -w 1 --timeout 60 main:app
#   no longer needed since renaming breadsheet.py --> main.py, and renaming 'breadapp' --> 'app'

error_handlers:
  - file: app/templates/errors/default_error.html

  - error_code: over_quota
    file: app/templates/errors/over_quota.html

# beta_settings:
#   cloud_sql_instances: breadsheet:us-west1:breadsheet

# env_variables:
#   SQLALCHEMY_DATABASE_URI: postgres+psycopg2://USER:PW@/breadsheet?host=/cloudsql/breadsheet:us-west1:breadsheet

includes:
  - env_variables.yaml
