"""create r&s tables

Revision ID: 0d1d0d89980b
Revises: 
Create Date: 2019-02-16 10:30:16.110381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1d0d89980b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=6), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_author'), 'recipe', ['author'], unique=False)
    op.create_index(op.f('ix_recipe_date_added'), 'recipe', ['date_added'], unique=False)
    op.create_index(op.f('ix_recipe_difficulty'), 'recipe', ['difficulty'], unique=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=True)
    op.create_index(op.f('ix_recipe_source'), 'recipe', ['source'], unique=False)
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('text', sa.LargeBinary(), nullable=True),
    sa.Column('then_wait', sa.Integer(), nullable=True),
    sa.Column('wait_time_range', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_number'), 'step', ['number'], unique=False)
    op.create_index(op.f('ix_step_text'), 'step', ['text'], unique=False)
    op.create_index(op.f('ix_step_then_wait'), 'step', ['then_wait'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_then_wait'), table_name='step')
    op.drop_index(op.f('ix_step_text'), table_name='step')
    op.drop_index(op.f('ix_step_number'), table_name='step')
    op.drop_table('step')
    op.drop_index(op.f('ix_recipe_source'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_difficulty'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_date_added'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_author'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
