"""changed replacement.where to .scope (1/2)

Revision ID: 26ff6b2361c0
Revises: 7f0b919bb42d
Create Date: 2019-02-18 21:14:02.292519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ff6b2361c0'
down_revision = '7f0b919bb42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replacement', sa.Column('scope', sa.String(length=1), nullable=True))
    op.alter_column('replacement', 'where',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replacement', 'where',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_column('replacement', 'scope')
    # ### end Alembic commands ###
