"""difficulty table

Revision ID: c0a8430af76b
Revises: 0d1d0d89980b
Create Date: 2019-02-18 14:32:44.147596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a8430af76b'
down_revision = '0d1d0d89980b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('id', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_step_then_wait', table_name='step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_step_then_wait', 'step', ['then_wait'], unique=False)
    op.drop_table('difficulty')
    # ### end Alembic commands ###
